In [ ]:
import numpy as np
from numpy.linalg import inv
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Solve page 172 XOR problem in closed form with linear model
Here we solve the equation 

$$w = (X^T X)^{-1} X^T y$$

where X is the training data and y is the label vector.

In [ ]:
x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y = np.array([0, 1, 1, 0])
x.T @ x
xinv = inv(x.T @ x)
xinv
w = xinv @ (x.T @ y)
w
# check that the computation is the same as the solution in the book
np.allclose(np.array([0, 0, 0.5]), w) 

array([[2, 1, 2],
       [1, 2, 2],
       [2, 2, 4]])

array([[ 1.00000000e+00, -1.11022302e-16, -5.00000000e-01],
       [ 0.00000000e+00,  1.00000000e+00, -5.00000000e-01],
       [-5.00000000e-01, -5.00000000e-01,  7.50000000e-01]])

array([0.00000000e+00, 2.22044605e-16, 5.00000000e-01])

True